name: hats2024
channels:
  - conda-forge
dependencies:
  - python
  - pip

  - coffea==2024.6.1

  - dask
  - dask-gateway

  - xrootd
  - prometheus_client
  - ipykernel
  - ipywidgets
  - root
  - root_base

  - scikit-hep-testdata
  - graphviz
  - python-graphviz
  - pydot
  - mimesis

  - pip:
    - fsspec-xrootd
    - rucio-clients